---
sidebar: false
---

# Frequently Asked Questions

## Our Objective

Our primary objective is to deliver comprehensive, evidence-based
neuropsychological evaluations for children, adolescents, and adults. We excel in
identifying and proposing solutions for a multitude of conditions, including but
not limited to ADHD, learning disabilities such as dyslexia, autism spectrum
disorders and more.

## Our Professional Services

- **Comprehensive Neuropsychological Evaluations:** We conduct meticulous evaluations to determine cognitive strengths and weaknesses.

- **Consultation and Proposals:** Customized strategies and assistance for parents and educators.

- **Follow-up and Assistance:** Persistent support and follow-up services, tailored to the individual needs of each patient.

## Fee Structure
The cost for evaluations varies based on the services required. A standard neuropsychological evaluation may range from $2200-3500, contingent upon referral questions and various other factors. We encourage you to contact our office for further information tailored to your specific situation.

The fee for intervention services and whether the intervention is a covered insurance benefit differ by the type of intervention and a patient’s specific insurance plan. We advise you to reach out to our office with any queries.

## Payment Procedure
### Insurance Coverage
Numerous insurance companies provide coverage for neuropsychological
evaluations. We recommend that you verify with your insurance provider to
ascertain your benefits. If applicable, you will be expected to fulfill
insurance deductibles at the time of service. Our office can furnish you with
more detailed information.

### Referrals
It is imperative that you 1) ascertain whether your insurance necessitates a referral and 2) ensure you have procured a referral prior to your scheduled appointment with one of our doctors. Referrals typically come with an expiration date and a limited number of visits, hence, it is crucial to track the dates and visits. Our office will not accommodate a patient who does not possess a valid referral.

### Authorizations
In case your insurance company mandates authorization for a neuropsychological evaluation, we will complete the necessary paperwork subsequent to the consultation visit. If your doctor is not an “in network provider,” you will need to provide us with the required documents. Authorizations for initial consult visits, if necessary, must be procured through your regular doctor or specialist.

Please note that school advocacy is not a benefit covered by insurance plans. The fee is $300 for the initial hour and $75 for each succeeding 15 minutes.

## Payments
We accept Health Savings Account/Flexible Spending Account plans, MasterCard, Visa, and Discover cards, in addition to cash and checks.

### Returned Checks
Should a check be returned, your account will be charged a $25 fee for each occurrence. Furthermore, you will be requested to bring cash to our office to cover the returned check fee.

