project:
  type: website

website:
  title: "blog"
  site-url: https://brainworkup.org/blog/
  image: images/logo.png
  favicon: images/favicon.png
  sidebar:
    style: "docked"
    contents:
      - blog.qmd
    search: true
    title: "**blog**"
    tools:
      - icon: github
        href: https://github.com/brainworkup/brainworkup/
        aria-label: Github
      - icon: twitter
        href: https://twitter.com/brainworkup/
        aria-label: Twitter
      - icon: instagram
        href: https://instagram.com/brainworkup/
        aria-label: Instagram
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/joey-trampush-brainworkup/
      - icon: rss
        href: https://brainworkup.org/blog/index.xml
        aria-label: RSS
