# Adult Services

At BrainWorkUp, we offer a range of specialized services to address various neuropsychological needs. Our approach is thorough, compassionate, and tailored to each individual.

## Consultation

An initial consultation is scheduled to gather relevant background information. This is a good time to ask specific questions and address concerns you may have. We can provide the highest quality of service by working collaboratively with you. If further testing is warranted, a testing appointment will be made at that time.

## Testing & Evaluation

The testing session is conducted by a trained psychometrist and may last from 2-8 hours, depending on the referral question, nature of the problem, and availability of previous testing results. Of course, you will be allowed to take breaks as needed.

## Feedback Session

Following the evaluation, a feedback session with you and your family may be conducted to discuss results and recommendations. With consent, other professionals involved in treatment may participate and/or receive information about the evaluation.

---

© 2023 BrainWorkUp - Comprehensive Neuropsychological Services
