- title: Pediatric Neuropsychology
  subtitle: Child and adolescent neurocognitive assessment
  links:
    - text: Pediatric Services Overview
      href: ../pediatric-neuropsychology/index.qmd
    - text: Preschoolers
      href: ../pediatric-neuropsychology/preschool.qmd
    - text: School-Age Children
      href: ../pediatric-neuropsychology/school-age.qmd

- title: Forensic Neuropsychology
  subtitle: 'Neurocognitive examination for forensic and medicolegal cases'
  links:
    - text: Forensic Services Overview
      href: ../forensic-neuropsychology/index.qmd
    - text: Independent Medical Examination
      href: ../forensic-neuropsychology/ime.qmd
    - text: Mental Health Diversion
      href: ../forensic-neuropsychology/mental-health-diversion.qmd

- title: Adult Neuropsychology
  subtitle: 'Neuropsychology of emerging adulthood'
  links:
    - text: Emerging Adulthood
      href: ../adult-neuropsychology/index.qmd
    - text: Adult-Onset ADHD
      href: ../adult-neuropsychology/adhd-adults.qmd

- title: Specific Disorders
  subtitle: 'Specialize in ADHD, LD, autism, OCD/perfectionism, and executive dysfunction'
  links:
    - text: ADHD
      href: ../disorders/adhd.qmd
    - text: Executive Dysfunction
      href: ../disorders/executive-function.qmd
    # - text: OCD and Pathological Perfectionism
    #   href: ../disorders/ocd.qmd
    # - text: Autism Spectrum Disorder
    #   href: ../disorders/autism.qmd
    - text: Dyslexia
      href: ../disorders/dyslexia.qmd
    - text: Testing Accommodations
      href: ../disorders/mcat.qmd
