- title: Pediatric Neuropsychology
  subtitle: Child and adolescent neurocognitive assessment
  links:
    - text: Neurodevelopmental Evaluations
      href: ../pediatric-neuropsychology/index.qmd
    - text: Preschoolers
      href: ../pediatric-neuropsychology/preschool.qmd
    - text: School-Age Children
      href: ../pediatric-neuropsychology/school-age.qmd
    - text: Adolescents
      href: ../pediatric-neuropsychology/adolescent.qmd

- title: Adult Neuropsychology
  subtitle: 'Neuropsychology of emerging adulthood including adult-onset ADHD'
  links:
    - text: 'Overview'
      href: ../adult-neuropsychology/index.qmd
    - text: 'Emerging Adulthood'
      href: ../adult-neuropsychology/emerging-adulthood.qmd
    - text: 'Adult-Onset ADHD'
      href: ../adult-neuropsychology/adult-onset-adhd.qmd

- title: Forensic Neuropsychology
  subtitle: Neurocognitive examination for forensic and medicolegal cases
  links:
    - text: General Forensic Services
      href: ../forensic-neuropsychology/index.qmd
    - text: Independent Medical Exams
      href: ../forensic-neuropsychology/ime.qmd
    - text: Mental Health Diversion
      href: ../forensic-neuropsychology/mental-health-diversion.qmd

- title: Specific Disorders
  subtitle: 'We have unique expertise in evaluating the disorders described below'
  links:
    - text: ADHD
      href: ../disorders/adhd.qmd
    - text: Test Accommodations
      href: ../disorders/mcat.qmd
    - text: Dyslexia
      href: ../disorders/dyslexia.qmd
    - text: Executive Dysfunction
      href: ../disorders/executive-function.qmd
    # - text: OCD and Pathological Perfectionism
    #   href: ../disorders/ocd.qmd
    - text: Autism
      href: ../disorders/autism.qmd
    - text: Sports-Related Concussions
      href: ../disorders/concussion.qmd
