- title: Pediatric Neuropsychology
  subtitle: Child and adolescent neurocognitive assessment
  links:
    - text: Overview
      href: ../pediatric-neuropsychology/index.qmd
    - text: Preschoolers
      href: ../pediatric-neuropsychology/preschool.qmd
    - text: School-Age Children
      href: ../pediatric-neuropsychology/school-age.qmd
    - text: Adolescents
      href: ../pediatric-neuropsychology/adolescent.qmd

- title: Forensic Neuropsychology
  subtitle: Neurocognitive examination for forensic and medicolegal cases
  links:
    - text: Overview
      href: ../forensic-neuropsychology/index.qmd
    - text: Independent Medical Examinations
      href: ../forensic-neuropsychology/ime.qmd
    - text: Mental Health Diversion
      href: ../forensic-neuropsychology/mental-health-diversion.qmd

- title: 'Adult Neuropsychology'
  subtitle: 'Neuropsychology of emerging adulthood including late-onset ADHD'
  links:
    - text: 'Overview'
      href: ../adult-neuropsychology/index.qmd
    - text: 'Emerging Adulthood'
      href: ../adult-neuropsychology/emerging-adulthood.qmd
    - text: 'Late-Onset ADHD'
      href: ../adult-neuropsychology/adult-onset-adhd.qmd

- title: Specific Disorders
  subtitle: Areas of expertise include ADHD, dyslexia and learning disorders, autism and Asperger's, OCD and perfectionism, and executive dysfunction
  links:
    - text: Overview
      href: ../disorders/index.qmd
    - text: ADHD
      href: ../disorders/adhd.qmd
    - text: Executive Dysfunction
      href: ../disorders/executive-function.qmd
    # - text: OCD and Pathological Perfectionism
    #   href: ../disorders/ocd.qmd
    # - text: Autism Spectrum Disorder
    #   href: ../disorders/autism.qmd
    - text: Dyslexia
      href: ../disorders/dyslexia.qmd
    - text: Sports-Related Concussion
      href: ../disorders/concussion.qmd
    - text: Testing Accommodations
      href: ../disorders/mcat.qmd
