project:
  title: "brainworkup"
  type: website
  output-dir: _site
  preview:
    port: 3000
    browser: true

website:
  title: "brainworkup"
  image: "bwu-logo.png"
  favicon: "favicon.png"
  open-graph: true
  twitter-card:
    creator: "@brainworkup"
    site: "@brainworkup"
    card-style: "summary_large_image"
  site-url: https://brainworkup.org
  repo-url: https://github.com/brainworkup/brainworkup
  issue-url: https://github.com/brainworkup/brainworkup/issues
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  google-analytics: "G-HW85H7H8P6"
  back-to-top-navigation: true
  reader-mode: true
  search:
    show-item-context: true
    type: overlay # more todo here
  page-footer:
    left: |
      **&copy; 2023 joey trampush, phd @ brainworkup, llc**
    center:
      - text: "**FAQ**"
        href: docs/faq/index.qmd
    right:
      - text: "**Contact**"
        href: docs/contact/index.qmd

  navbar:
    background: dark
    foreground: light
    # logo: bwu-logo.png
    # logo-alt: "BWU logo."
    title: brainworkup
    collapse-below: lg
    left:
      - text: "Dr Trampush"
        href: docs/trampush/index.qmd
      - text: "Clinical Services"
        menu:
          - text: "Pediatric Neuropsychology"
            href: docs/services/pediatrics/index.qmd
          - text: "Adult Neuropsychology"
            href: docs/services/adult/index.qmd
          - text: "Forensic Neuropsychology"
            href: docs/services/forensic/index.qmd
      - text: "Research"
        menu:
          - text: "Projects"
            href: docs/research/projects/index.qmd
          - text: "Publications"
            href: docs/research/publications/index.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
      - text: "Contact"
        href: docs/contact/index.qmd
      - text: "Blog"
        href: docs/blog/index.qmd

    right:
      - icon: github
        href: https://github.com/brainworkup/brainworkup
        aria-label: Brainworkup Github
      - icon: twitter
        href: https://twitter.com/brainworkup
        aria-label: brainworkup Twitter
      - icon: instagram
        href: https://instagram.com/brainworkup
        aria-label: brainworkup Instagram

  sidebar:
    contents:
      - section: "Clinical Services"
        contents: "docs/services/*/index.qmd"
      - section: "Contact"
        contents: "docs/contact"
      - section: "General Information"
        contents: "docs/faq"
      # contents: auto
    type: dark
    style: floating #docked
    collapse-level: 1
    align: left

bibliography: refs.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem

metadata-files: [brain2.yml]

execute:
  freeze: auto
