project:
  type: website
  output-dir: _site
  resources:
    - "*.webp"
    - "*.png"
    - "*.jpg"
    - "*.jpeg"
    - "*.svg"
    - "*.ico"
    - "*.pdf"
    - "*.txt"
    - "site_libs/"
    - "_redirects"
    - "_headers"
    - "CNAME"
    - ".nojekyll"

website:
  title: "BrainWorkup Neuropsychology"
  site-url: https://brainworkup.org
  description: "Expert neuropsychological evaluations for ADHD, dyslexia, learning disorders, autism, and forensic assessments in Los Angeles and Southern California."
  favicon: favicon.png
  repo-actions: "none"
  open-graph: true
  twitter-card: true
  search: true

  # Global navigation
  navbar:
    logo: logo.webp
    background: "#F9FBFC"
    pinned: true
    collapse: true
    right:
      - text: "Home"
        href: /index.html
      - text: "Services"
        menu:
          - text: "ADHD Testing"
            href: /adhd/index.html
          - text: "ADHD in Girls"
            href: /adhd-in-girls/index.html
          - text: "Adult-Onset ADHD"
            href: /adult-onset-adhd/index.html
          - text: "Autism Assessment"
            href: /autism/index.html
          - text: "Pediatric Services"
            href: /pediatric-neuropsychology/index.html
          - text: "Adult Services"
            href: /adult-neuropsychology/index.html
          - text: "Forensic Services"
            href: /forensic-neuropsychology/index.html
      - text: "About"
        href: /joey-trampush/index.html
      - text: "Contact"
        href: /contact/index.html

  # Footer shown on all pages
  page-footer:
    left: |
      © 2025 BrainWorkup Neuropsychology, LLC<br>
      4136 Del Rey Avenue, Suite 661<br>
      Marina del Rey, CA 90292
    center: |
      [Terms & Privacy Policy](/privacy.html)<br>
      [Contact Us](/contact/index.html)
    right: |
      [Call: (213) 495-1155](tel:2134951155)<br>
      [Email: info@brainworkup.org](mailto:info@brainworkup.org)<br>
      [Get Directions](https://goo.gl/maps/5Q4Z2jW2Z2Z2)

# Global format options applied to all pages
format:
  html:
    theme: cosmo
    css: styles.min.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/brainworkup\.org
    include-in-header: header.html
    include-after-body: common-scripts.html
    filters:
      - fix-relative-links.lua
    metadata:
      lang: en
    self-contained: false
    anchor-sections: true
