project:
  title: 'brainworkup'
  type: website
  output-dir: _site
  preview:
    port: 3000
    browser: true

website:
  title: 'Joey Trampush, PhD @ Brainworkup Neuropsychology, LLC'
  image: 'bwu-logo.png'
  favicon: 'favicon.png'
  open-graph: true
  twitter-card:
    creator: '@brainworkup'
    site: '@brainworkup'
    card-style: 'summary_large_image'
  site-url: 'https://brainworkup.org'
  site-path: '/'
  repo-url: https://github.com/brainworkup/brainworkup
  issue-url: https://github.com/brainworkup/brainworkup/issues
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  google-analytics: 'G-HW85H7H8P6'
  back-to-top-navigation: true
  reader-mode: false
  search:
    show-item-context: true
    type: overlay
    algolia:
      index-name: dev_BWU
      application-id: 'MUSKCL25U0'
      search-only-api-key: '88aa5eda961e038670ae6e8aa6e60687'
      analytics-events: true
      show-logo: false
  page-footer:
    left: |
      &copy; 2023 joey trampush @ brainworkup
    center:
      - text: 'About'
        href: docs/about/joey-trampush.qmd
      - text: 'FAQ'
        href: docs/faq/index.qmd
      - text: 'Contact'
        href: docs/contact/index.qmd
    right:
      - icon: github
        href: https://github.com/brainworkup/brainworkup
        aria-label: Brainworkup Github
      - icon: twitter
        href: https://twitter.com/brainworkup
        aria-label: Brainworkup Twitter
      - icon: instagram
        href: https://instagram.com/brainworkup
        aria-label: Brainworkup Instagram

  navbar:
    background: dark
    foreground: light
    title: 'brainworkup'
    collapse-below: lg
    left:
      - text: 'Dr Trampush'
        href: docs/about/joey-trampush.qmd
      - text: 'Neuropsychological Services'
        href: docs/clinical-services/index.qmd
      - text: 'Research'
        href: docs/research/index.qmd
      - text: 'FAQ'
        href: docs/faq/index.qmd
      - text: 'Contact'
        href: docs/contact/index.qmd
      - text: 'Blog'
        href: docs/blog/index.qmd
      - icon: file-pdf
        text: CV
        href: /files/cv.pdf

    right:
      - icon: envelope
        text: info@brainworkup.org
        href: mailto:info@brainworkup.org

    tools:
      - icon: github
        href: https://github.com/brainworkup/brainworkup
        aria-label: brainworkup Github
      - icon: twitter
        href: https://twitter.com/brainworkup
        aria-label: brainworkup Twitter
      - icon: instagram
        href: https://instagram.com/brainworkup
        aria-label: brainworkup Instagram
      - icon: linkedin
        aria-label: brainworkkup LinkedIn
        href: https://www.linkedin.com/in/joey-trampush-brainworkup/
      - icon: rss
        href: https://brainworkup.org/docs/blog/index.xml
        aria-label: BWU Blog RSS

  sidebar:
    - id: trampush
      title: 'About'
      style: 'floating'
      collapse-level: 1
      align: left
      contents:
        - docs/about/joey-trampush.qmd

    - id: clinical-services
      collapse-level: 1
      contents:
        - section: 'Clinical Services'
          href: docs/clinical-services/index.qmd
          contents:
            - section: 'Pediatric Neuropsychology'
              contents:
                - docs/pediatric-neuropsychology/index.qmd
            - section: 'Forensic/Medicolegal'
              contents:
                - docs/forensic-neuropsychology/index.qmd
            - section: 'ADHD'
              contents:
                - docs/adhd-evaluation/adhd.qmd
                - docs/adhd-evaluation/mcat.qmd

    - id: research
      title: 'Research'
      collapse-level: 2
      contents:
        - section: 'Research'
          href: docs/research/index.qmd
          contents:
            - section: 'Projects'
              contents:
                - docs/projects/index.qmd
            - section: 'Publications'
              contents:
                - docs/publications/index.qmd

    - id: faq
      title: 'FAQ'
      collapse-level: 1
      contents:
        - section: 'FAQ'
          href: docs/faq/index.qmd

    - id: contact
      title: 'Contact Us'
      collapse-level: 1
      contents:
        - section: 'Contact Us'
          href: docs/contact/index.qmd

bibliography: refs.bib

format:
  html:
    toc: true
    toc-depth: 4
    theme:
      light: [cosmo, css/theme.scss]
    css: css/styles.css
    include-after-body: js.html
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    fontsize: 1.2em
    linestretch: 1.14
    highlight-style: dracula
    link-external-icon: true
    link-external-newwindow: true

metadata-files: [brain2.yml]

execute:
  freeze: true
  cache: true

editor: source
