project:
  title: 'brainworkup'
  type: website
  output-dir: _site
  preview:
    port: 3000
    browser: true

website:
  title: 'Joey Trampush, PhD @ Brainworkup Neuropsychology, LLC'
  image: 'logo.png'
  favicon: 'logo.ico'
  open-graph: true
  twitter-card:
    creator: '@brainworkup'
    site: '@brainworkup'
    card-style: 'summary_large_image'
  site-url: https://brainworkup.org
  site-path: '/'
  repo-url: https://github.com/brainworkup/brainworkup
  repo-branch: origin
  issue-url: https://github.com/brainworkup/brainworkup/issues
  repo-actions: [issue]
  page-navigation: true
  bread-crumbs: true
  google-analytics: 'G-HW85H7H8P6'
  back-to-top-navigation: true
  reader-mode: false
  search:
    show-item-context: true
    type: overlay
    algolia:
      index-name: netlify_104efd43-d6ca-45be-b3cc-806c026e306c_main_all
      application-id: MUSKCL25U0
      search-only-api-key: 88aa5eda961e038670ae6e8aa6e60687
      analytics-events: true
      show-logo: true
      index-fields:
        href: https://brainworkup.org/search.json
        section: sec
        text: body
  page-footer:
    left: |
      ![](/logo.webp){fig-alt="brainworkup" width=85px} &copy; 2023 joey trampush @ brainworkup
    center:
      - text: 'About'
        href: docs/about/joey-trampush.qmd
      - text: 'FAQ'
        href: docs/faq/index.qmd
      - text: 'Contact'
        href: docs/contact/index.qmd
    right:
      - icon: github
        href: https://github.com/brainworkup/brainworkup
        aria-label: Github
      - icon: twitter
        href: https://twitter.com/brainworkup
        aria-label: Twitter
      - icon: instagram
        href: https://instagram.com/brainworkup
        aria-label: Instagram
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/joey-trampush-brainworkup/
      - icon: rss
        href: https://brainworkup.org/docs/blog/index.xml
        aria-label: RSS

  navbar:
    title: 'brainworkup'
    background: dark
    foreground: light
    collapse-below: lg
    left:
      - text: 'Dr Trampush'
        href: docs/about/joey-trampush.qmd
      - text: 'Neuropsychological Services'
        href: docs/clinical-services/index.qmd
      - text: 'FAQ'
        href: docs/faq/index.qmd
      - text: 'Contact'
        href: docs/contact/index.qmd
      - text: 'Blog'
        href: docs/blog/index.qmd
      - icon: file-pdf
        text: 'CV'
        href: /files/cv.pdf
    right:
      - icon: phone
        text: '**(213) 495-1155**'
        href: tel:2134951155
      - icon: envelope
        text: '**info@brainworkup.org**'
        href: mailto:info@brainworkup.org
    tools:
      - icon: github
        href: https://github.com/brainworkup/brainworkup
        aria-label: Github
      - icon: twitter
        href: https://twitter.com/brainworkup
        aria-label: Twitter
      - icon: instagram
        href: https://instagram.com/brainworkup
        aria-label: Instagram
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/joey-trampush-brainworkup/
      - icon: rss
        href: https://brainworkup.org/docs/blog/index.xml
        aria-label: RSS

  sidebar:
    - id: trampush
      title: 'About'
      style: 'floating'
      collapse-level: 1
      align: left
      contents:
        - docs/about/joey-trampush.qmd

    - id: clinical-services
      search: true
      collapse-level: 3
      contents:
        - section: 'Neuropsychological Services'
          href: docs/clinical-services/index.qmd
          contents:
            - section: '**Pediatric Neuropsychology**'
              contents:
                - docs/pediatric-neuropsychology/index.qmd
                - docs/pediatric-neuropsychology/preschool.qmd
                - docs/pediatric-neuropsychology/school-age.qmd
                - docs/pediatric-neuropsychology/adolescent.qmd
            - section: '**Adult Neuropsychology**'
              contents:
                - docs/adult-neuropsychology/index.qmd
                - docs/adult-neuropsychology/emerging-adulthood.qmd
                - docs/adult-neuropsychology/adult-onset-adhd.qmd
            - section: '**Forensic Neuropsychology**'
              contents:
                - docs/forensic-neuropsychology/index.qmd
                - docs/forensic-neuropsychology/ime.qmd
                - docs/forensic-neuropsychology/mental-health-diversion.qmd
            - section: '**Specific Disorders**'
              contents:
                - docs/disorders/index.qmd
                - docs/disorders/adhd.qmd
                - docs/disorders/dyslexia.qmd
                - docs/disorders/executive-function.qmd
                - docs/disorders/concussion.qmd
                - docs/disorders/mcat.qmd

    # - id: research
    #   title: 'Research'
    #   collapse-level: 2
    #   contents:
    #     - section: 'Research'
    #       href: docs/research/index.qmd
    #       contents:
    #         - section: 'Projects'
    #           contents:
    #             - docs/projects/index.qmd
    #         - section: 'Publications'
    #           contents:
    #             - docs/publications/index.qmd

    - id: faq
      title: 'FAQ'
      collapse-level: 1
      contents:
        - section: 'FAQ'
          href: docs/faq/index.qmd

    - id: contact
      title: 'Contact'
      collapse-level: 1
      contents:
        - section: 'Contact Us'
          href: docs/contact/index.qmd

bibliography: refs.bib

search: true

format:
  html:
    toc: true
    toc-depth: 4
    toc-expand: 1
    toc-title: '**On this page**'
    theme:
      light: [cosmo, theme.scss]
    css: styles.css
    include-after-body: js.html
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    grid:
      sidebar-width: 350px
      body-width: 900px
      margin-width: 250px
      gutter-width: 1.5rem
    fontsize: 1.2em
    linestretch: 1.14
    highlight-style: dracula
    linkcolor: '#1e2e51'
    link-external-icon: true
    link-external-newwindow: true
    fig-align: center
    author-meta: 'Joey Trampush'
    lightbox: true

metadata-files: [brain2.yml]

execute:
  freeze: true
  cache: true

editor: source
