project:
  title: "brainworkup"
  type: website
  output-dir: _site
  preview:
    port: 3000
    browser: true

website:
  title: "brainworkup"
  image: "bwu-logo.png"
  favicon: "favicon.png"
  open-graph: true
  twitter-card:
    creator: "@brainworkup"
    site: "@brainworkup"
    card-style: "summary_large_image"
  site-url: https://brainworkup.org
  repo-url: https://github.com/brainworkup/brainworkup
  issue-url: https://github.com/brainworkup/brainworkup/issues
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  google-analytics: "G-HW85H7H8P6"
  back-to-top-navigation: true
  reader-mode: false
  search:
    show-item-context: true
    type: overlay
    algolia:
      index-name: prod_netlify_brainworkup
      application-id: MUSKCL25U0
      search-only-api-key: 88aa5eda961e038670ae6e8aa6e60687
      analytics-events: true
      show-logo: true
  page-footer:
    left: |
      **&copy; 2023 joey trampush, phd @ brainworkup, llc**
    center:
      - text: "**FAQ**"
        href: docs/faq/index.qmd
    right:
      - text: "**Contact**"
        href: docs/contact/index.qmd

  navbar:
    background: dark
    foreground: light
    title: brainworkup
    collapse-below: lg
    left:
      - text: "Dr Trampush"
        href: docs/trampush/index.qmd
      - icon: file-pdf
        text: CV
        href: /files/cv.pdf
      - text: "Clinical Services"
        menu:
          - text: "Pediatric Neuropsychology"
            href: docs/services/pediatrics/index.qmd
          - text: "Adult Neuropsychology"
            href: docs/services/adult/index.qmd
          - text: "Forensic Neuropsychology"
            href: docs/services/forensic/index.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
      - text: "Contact"
        href: docs/contact/index.qmd
      - text: "Research"
        href: docs/research/index.qmd
        menu:
          - text: "Projects"
            href: docs/research/projects/index.qmd
          - text: "Publications"
            href: docs/research/publications/index.qmd
      - text: "Blog"
        href: docs/blog/index.qmd

    right:
      - icon: envelope
        # text: E-mail
        href: mailto:info@brainworkup.org
      - icon: github
        href: https://github.com/brainworkup/brainworkup
        aria-label: brainworkup Github
      - icon: twitter
        href: https://twitter.com/brainworkup
        aria-label: brainworkup Twitter
      - icon: instagram
        href: https://instagram.com/brainworkup
        aria-label: brainworkup Instagram
      - icon: linkedin
        aria-label: brainworkkup LinkedIn
        href: https://www.linkedin.com/in//joey-trampush-brainworkup/
      - icon: rss
        href: https://brainworkup.org/docs/blog/index.xml
        aria-label: BWU Blog RSS

  sidebar:
    search: true
    title: brainworkup
    # contents: auto
    contents:
      - section: "Dr Trampush"
        contents: "docs/trampush"
      - section: "Clinical Services"
        contents: "docs/services/**"
      - section: "FAQ"
        contents: "docs/faq"
      - section: "Contact Us"
        contents: "docs/contact"
      - section: "Research"
        contents: "docs/research/**"
      - section: "Blog"
        contents: "docs/blog"
    type: dark
    style: floating
    collapse-level: 1
    align: left

bibliography: refs.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    smooth-scroll: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px
      gutter-width: 1.5rem
    fontsize: 1.2em
    linestretch: 1.4
    default-image-extension: svg

metadata-files: [brain2.yml]

execute:
  freeze: auto
