- title: Pediatric Neuropsychology
  subtitle: Child and adolescent neurocognitive assessment
  links:
    - text: Neurodevelopment
      href: ../docs/pediatric-neuropsychology/index.qmd
    - text: Preschoolers
      href: ../docs/pediatric-neuropsychology/preschool/index.qmd
    - text: School-Age Children
      href: ../docs/pediatric-neuropsychology/school-age/index.qmd
    - text: Adolescents
      href: ../docs/pediatric-neuropsychology/adolescent/index.qmd

- title: Adult Neuropsychology
  subtitle: Neuropsychology of emerging adulthood including adult-onset ADHD
  links:
    - text: "Overview"
      href: ../docs/adult-neuropsychology/index.qmd
    - text: "Emerging Adulthood"
      href: ../docs/adult-neuropsychology/emerging-adulthood/index.qmd
    - text: "Adult-Onset ADHD"
      href: ../docs/adult-neuropsychology/adult-onset-adhd/index.qmd

- title: Forensic Neuropsychology
  subtitle: Neurocognitive examination for forensic and medicolegal cases
  links:
    - text: General Forensic Services
      href: ../docs/forensic-neuropsychology/index.qmd
    - text: Independent Medical Exams
      href: ../docs/forensic-neuropsychology/independent-medical-exam/index.qmd
    - text: Mental Health Diversion
      href: ../docs/forensic-neuropsychology/mental-health-diversion/index.qmd

- title: Conditions Treated
  subtitle: "We have unique expertise in evaluating the neurocognitive and neurobehavioral conditions described below"
  links:
    # - text: Specialty Areas
    #   href: ../docs/conditions-treated/index.qmd
    - text: ADHD
      href: ../docs/conditions-treated/adhd/index.qmd
    - text: ADHD in Girls
      href: ../docs/conditions-treated/adhd-in-girls/index.qmd
    - text: Test Accommodations
      href: ../docs/conditions-treated/testing-accommodations/index.qmd
    - text: Dyslexia
      href: ../docs/conditions-treated/dyslexia/index.qmd
    - text: Executive Dysfunction
      href: ../docs/conditions-treated/executive-function/index.qmd
    # - text: OCD and Pathological Perfectionism
    #   href: ../docs/conditions-treated/ocd/index.qmd
    - text: Autism
      href: ../docs/conditions-treated/autism/index.qmd
    - text: Sports-Related Concussions
      href: ../docs/conditions-treated/concussion/index.qmd
