- title: Pediatric Neuropsychology
  subtitle: Child and adolescent neurocognitive assessment
  links:
    - text: "Neurodevelopment"
      href: pediatric-neuropsychology/index.qmd
    - text: "Preschoolers"
      href: pediatric-neuropsychology/preschool/index.qmd
    - text: "School-Age Children"
      href: pediatric-neuropsychology/school-age/index.qmd
    - text: "Adolescents"
      href: pediatric-neuropsychology/adolescent/index.qmd

- title: Adult Neuropsychology
  subtitle: Neuropsychology of emerging adulthood including adult-onset ADHD
  links:
    - text: "Overview"
      href: adult-neuropsychology/index.qmd
    - text: "Emerging Adulthood"
      href: /emerging-adulthood/index.qmd
    - text: "Adult-Onset ADHD"
      href: /adult-onset-adhd/index.qmd

- title: Forensic Neuropsychology
  subtitle: Neurocognitive examination for forensic and medicolegal cases
  links:
    - text: "General Forensic Services"
      href: forensic-neuropsychology/index.qmd
    - text: "Independent Medical Exams"
      href: /independent-medical-exam/index.qmd
    - text: "Mental Health Diversion"
      href: /mental-health-diversion/index.qmd

- title: Conditions Treated
  subtitle: "We have unique expertise in evaluating the neurocognitive and neurobehavioral conditions described below"
  links:
    - text: Specialty Areas
      href: conditions-treated/index.qmd
    - text: ADHD
      href: /adhd/index.qmd
    - text: ADHD in Girls
      href: /adhd-in-girls/index.qmd
    - text: Test Accommodations
      href: /testing-accommodations/index.qmd
    - text: Dyslexia
      href: /dyslexia/index.qmd
    - text: Executive Dysfunction
      href: /executive-function/index.qmd
    # - text: OCD and Pathological Perfectionism
    #   href: /conditions-treated/ocd/index.qmd
    - text: Autism
      href: /autism/index.qmd
    - text: Sports-Related Concussions
      href: /concussion/index.qmd
