---
title: "Dyslexia Evaluations"
format: html
---

Dyslexia evaluations are a common type of learning disorder assessment conducted to determine eligibility for academic and workplace accommodations. Approximately 15-20% of the general population (around 30 million people in the United States) exhibit signs of dyslexia.

Our comprehensive evaluations identify cognitive and academic strengths and weaknesses, helping to pinpoint the underlying cause of reading difficulties.

Working closely with you, your family, and your teachers, we provide practical feedback and recommendations for accommodations to enhance your performance in educational and professional settings.

## Dyslexia Definition

> *Dyslexia* means an individual has a neurobiologically based cognitive processing problem that affects how easily and efficiently they can learn to read. Dyslexia is a common condition: some experts believe 5-10% of people have it; others say as many as 17% of people show signs of reading challenges. Dyslexia is formally classified as a specific learning disability in reading. People with dyslexia have trouble reading at a good pace and without mistakes. They may also have a hard time with reading comprehension, spelling, and writing. Importantly, these challenges are not a problem with intelligence.
>
> Approximately 24% of individuals diagnosed with dyslexia are able to achieve reading skills commensurate with nondyslexic peers. A concept in the research literature is one of "compensated dyslexia"[@vanviersenHighReadingSkills2016], which is used to describe these individuals because they use strengths in other areas to compensate for deficits in reading. Dyslexia is underidentified in this population because the dyslexia can be masked by strengths in vocabulary and intelligence, making it especially difficult to identify in high-achieving individuals.

### Common complaints

- You read at a pace that is noticeably slower than average 
- You struggled to gain proficiency in reading while in school  
- You often have to reread passages multiple times before understanding them 
- When reading or writing, you often leave out certain letters or mix them up 
- Spelling words incorrectly is something that happens frequently for you 
- When attempting to read aloud, you find it difficult to correctly pronounce multi-syllabic words 
- Instead of tackling longer books, you prefer to read magazines and shorter articles 
- To dodge reading-intensive tasks, you tend to avoid working on projects that require

## Dyslexia: Identification and Accommodations

Dyslexia often presents as difficulties in reading and writing, potentially affecting academic performance. If diagnosed with dyslexia, the Americans with Disabilities Act (ADA) may entitle you to reasonable accommodations at school or work.

Our aim is to assist you in identifying dyslexia and recommend suitable accommodations. We employ psychological testing, behavioral observations, and consultations with your educational institution for accurate diagnosis and treatment recommendations.

Academic adjustments like additional time, extended breaks, or a private room can help mitigate the impact of dyslexia, enabling you to perform at your fullest potential.

Accommodations can be provided for the following standardized tests:

- ACT
- SAT
- GMAT
- GRE
- LSAT
- MCAT
- PCAT
- State of California Bar Exam
- Any other standardized test or professional licensing exam

## Dyslexia Evaluation Process

Our evaluation for dyslexia includes:

- A clinical interview to gather background information on psychological, medical, educational, and social aspects, alongside current cognitive and psychological functioning.
- Review of relevant medical, psychological, and educational records for a comprehensive understanding of your psychological and academic history.
- Administration of psychological and neuropsychological tests to assess various cognitive and educational aspects, including:
  - Intellectual abilities
  - Academic skills (reading, writing, spelling, math)
  - Executive functions (reasoning, problem-solving)
  - Attention and concentration
  - Language and communication
  - Visual-spatial abilities
  - Memory
  - Motor and sensory skills
  - Emotional and personality assessment
  - Psychological diagnosis

Following the evaluation, we will compile a detailed report integrating our findings. This report will be provided to you, your school, and any relevant organizations for academic accommodations. Additionally, a feedback session will be conducted to discuss the results and treatment recommendations. This evaluation aims to identify dyslexia and facilitate necessary academic support.
