---
title: "Adolescents"
description: >
  Explore the complexities of adolescence and its impact on cognitive abilities.
format: html
include-in-header: canonical-adolescent.html
# aliases:
#   - "../docs/pediatric-neuropsychology/adolescents/"
#   - "../services/pediatric-neuropsychology/adolescents/"
---

## Teenagers ...

Adolescence is a period of intensive physical, emotional and social change, and the academic and social demands of high school are stronger than ever. At the same time, the teen brain is “still under construction,” and striking changes in brain maturation take place during the teen years [link]. We can assess some of these changes in the clinic.

:::{.callout-tip collapse=false appearance='default' icon=true}
Add here a tip or a note
:::

As an example, in a series of research studies we carried out with colleagues in New York, we discovered that certain neurocognitive abilities were associated with a reduction in attention problems during adolescence [link], and that this relationship was influenced by genetics but only during later stages of development [link]. The more we learn about your teen, the better we may be able to understand and monitor his or her cognitive abilities (and vulnerabilities), which could influence your teen’s longer-term psychological health and well-being.

## Adoleascent Brain Development

Explore the complexities of adolescence and its impact on cognitive abilities. Understand the ongoing brain maturation during teen years, its influence on attention problems, and how genetics plays a role in later stages of development.

## 🚧 This Page is Under Construction 🚧

We're working hard to finish the development of this site. Our target launch
date is **Coming Soon**!

:::{.callout-note collapse=false appearance='default' icon=true}
Add here a note or a warning
:::
