---
title: "Untitled"
format: html
---

JUVENILE FORENSIC EVALUATIONS
Adolescents in the juvenile justice system often have undiagnosed mental health or neurodevelopmental conditions.

Psychological evaluations help identify issues related to childhood trauma, mental health conditions (e.g., depression, anxiety, PTSD) developmental immaturity, intellectual disabilities or borderline intellectual functioning, learning disabilities, and other neurodevelopmental conditions.

How We Can Help
We take a collaborative approach and work with the client, their family, mental health treatment providers, and attorney when we complete juvenile forensic evaluations. Psychological evaluations of juveniles assist with treatment recommendations and rehabilitation and can assist with the following situations: 

Competency to Stand Trial
Mitigation
Capacity to Waive Miranda Rights
Regional Center Referrals
Suitable Placements
What to Expect
A clinical interview with the minor and close members of their family. The interview will help us understand important psychological, medical, and social background information, and their current and past cognitive and psychological functioning.
Consultation with the minor’s attorney to determine the legal questions and issues that need to be addressed and answered in the report.
A review of medical, psychological, educational, and legal documents to help us have a better understanding of the minor’s psychological, cognitive, and emotional functioning.
Depending on the minor’s history and requirements for the case, we will administer psychological and neuropsychological tests to objectively assess for mental health diagnoses and cognitive abilities.  We will administer and interpret paper and computer-based tests to assess for:
General intellectual abilities
Adaptive functioning
Higher level executive skills such as reasoning and problem solving
Attention and concentration
Language comprehension and communication
Visual-spatial skills and perception
Memory impairment
Motor and sensory skills
Mood and personality
Psychological diagnoses
After we complete the evaluation, we will write a comprehensive report that integrates our findings and give it to the minor’s representative or attorney.
An evaluation will help you understand your client’s psychological and cognitive functioning to assist in preparing their defense
