---
title: "Untitled"
format: html
---

COMPETENCY EVALUATIONS
Competency or decision-making capacity is an individual’s mental capacity to make voluntary, reasonable, and rational choices.

Competent decision-making requires that the client can understand what is being discussed, appreciate the significance of the information, apply reasoning to the context of the situation, and express a choice based on their rationalization.

Our comprehensive evaluations can help answer competency questions in medical, civil, and criminal settings.

How We Can Help
We take a collaborative approach and work with the client, their family, physician, and attorney when we complete a competency evaluation. Our in-depth assessment will help identify the client’s ability to make voluntary, reasonable, and rational choices related to their medical care, civil case, or criminal case.

Medical
Competency in medical settings is the client’s ability to make voluntary, reasonable, and informed decisions related to their healthcare. Making an informed decision can have an immense impact on the client’s health and quality of life. A competency evaluation will help determine the client’s state of mind, functioning, and their ability to give informed consent.

Civil
Competency in civil settings can help determine if a client is competent to execute a will, determine medical directives related to long term care, assign power of attorney, open a trust account, agree to a settlement, or if they need to be placed into a conservatorship.

Criminal
Competency in a criminal setting is a court-ordered evaluation to determine if the defendant has the capacity and ability to have a rational and factual understanding of the proceedings against them and if they have the ability to consult with their attorney with a reasonable degree of rational understanding.

What to Expect
Competency can be difficult to measure and a comprehensive evaluation is essential to determine if a client is competent.  Our evaluation will assess for psychological and neuropsychological factors that can impact decision-making.

Our competency evaluations typically involve:

A clinical interview with the client and close members of their family. The interview will help us understand important psychological, medical, and social background information, and their current cognitive and psychological functioning.
Consultation with the client’s attorney or representative to determine the legal questions that need to be answered.
A review of medical, psychological, and other collateral documents that help us have a better understanding of the client’s psychological and emotional functioning.
We will administer psychological and neuropsychological tests to objectively assess for mental health diagnoses and cognitive abilities.  We will administer and interpret paper and computer-based tests to assess for:
General intellectual abilities
Higher level executive skills such as reasoning and problem solving
Attention and concentration
Language comprehension and communication
Visual-spatial skills and perception
Memory impairment
Motor and sensory skills
Mood and personality
Psychological diagnoses
After we complete the evaluation, we will write a comprehensive report that integrates our findings and give it to the client’s representative or attorney.
A psychological evaluation will identify your client’s ability to make rational choices in their civil or criminal case
