---
title: "Mental Health Diversion Evaluations"
format: html
---

In 2018, Governor Jerry Brown signed into law Senate Bill 215, which created a pre-trial diversion program for defendants with a mental disorder that has been accused of committing specific crimes. 

If they complete treatment, the criminal charges will be dismissed and the record of the arrest will be sealed.

## How We Can Help
We take a collaborative approach and work with the client, their family, mental health treatment providers, and attorney when we complete a mental health diversion evaluation.

Our in-depth assessment will help answer the following questions related to the mental health diversion criteria:

- Whether the defendant suffers from a mental disorder, excluding Antisocial Personality Disorder, Borderline Personality Disorder, and Pedophilic Disorder.
- Whether the mental disorder significantly contributed to the defendant’s involvement in the commission of the offense.
- Whether the defendant’s symptoms motivating the criminal behavior would respond to mental health treatment.
- Whether the defendant agrees to comply with treatment as a condition of diversion.
- Whether the defendant will pose an unreasonable risk of danger to public safety, as defined in PC 1170.18 if treated in the community.

## What to Expect
Our in-depth evaluation will help gather the necessary information to answer the relevant questions to help the court determine if the client is suitable for mental health diversion. 

Our mental health diversion evaluations typically involve:

A clinical interview with the client and close members of their family. The interview will help us understand important psychological, medical, and social background information, and their current cognitive and psychological functioning.
Consultation with the client’s attorney to determine the legal questions that need to be answered.
A review of medical, psychological, and legal documents to help us have a better understanding of the client’s psychological, cognitive, and emotional functioning leading up to and during the alleged offense.
- Depending on the client’s history and requirements for the case, we will administer psychological and neuropsychological tests to objectively assess for mental health diagnoses and cognitive abilities.  We will administer and interpret paper and computer-based tests to assess for:
  - General intellectual abilities
  - Higher level executive skills such as reasoning and problem solving
  - Attention and concentration
  - Language comprehension and communication
  - Visual-spatial skills and perception
  - Memory impairment
  - Motor and sensory skills
  - Mood and personality
  - Psychological diagnoses

We will complete a violence risk assessment to determine the appropriate course of treatment in the community and ways to mitigate future violence risk.
After we complete the evaluation, we will write a comprehensive report that integrates our findings and give it to the client’s representative or attorney.
A mental health diversion evaluation will determine if your client qualifies to attend treatment in the community
