---
created: 2023-12-14T17:21:38 (UTC -08:00)
tags: []
source: https://childmind.org/article/what-is-non-verbal-learning-disorder/
author: Caroline Miller
format: html
---

# What is Non-Verbal Learning Disorder | NVLD Symptoms | Child Mind Institute

> ## Excerpt
> What is non-verbal learning disorder? Child Mind Institute explains NLD symptoms, such as trouble understanding information, concepts, and ideas.

_This is the first in a series of articles about non-verballearning disorder developed in collaboration with [Winston Preparatory School](http://www.winstonprep.edu/), a New York area school that has taken a leading role in working with students with the disorder._

When we think of [learning disorders,](https://childmind.org/article/recognizing-learning-disorders-in-the-classroom/) we tend to think ofdyslexia and other disorders involving language—that is, kids who have trouble decoding language and learning to read.

But there is another, less well-known type of learning disorder that’s not about _verbal_ communication—hence it’s called [_non-verbal_ learning disorder](https://childmind.org/topics/disorders/nonverbal-learning-disorder/). You’ll see it referred to as NVLD or NLD. It isn’t an officialdiagnosis like [ADHD](https://childmind.org/guide/guide-to-attention-deficit-hyperactivity-disorder/) and [autism](https://childmind.org/guide/guide-to-austism-spectrum-disorder/)—in fact many kids who have non-verbal learning challenges have those diagnoses. But experts say focusing on NLD explains what’s happening with kids—and how to help them learn—better than those diagnoses.

## NLD and recognizing patterns

Kids who have NLD do not have trouble decoding language, reading, or learning information in a rote way. As Scott Bezsylko, executive director of Winston Preparatory School, puts it, “Think of it as the opposite of dyslexia.” The problems these kids have involve, he says, all the other kinds of learning. “All the stuff that involves understanding information—relationships, concepts, ideas, patterns.”

These deficits—all things related to the right hemisphere of the brain—can affect a child’s ability to do a surprising variety of things. Physical coordination, [social interaction](https://childmind.org/article/social-challenges-kids-learning-problems/), problem solving, organizing thoughts, planning—all these things can be challenging. They seem very different, but the unifying theme is that each requires the ability to recognize patterns or concepts and then apply them to new situations.

## The five areas of NLD

There are five areas in which [children with NLD](https://childmind.org/article/quick-facts-on-non-verbal-learning-disorder-nld/) show weakness. Not all children have weaknesses in all areas.

**1\. Visual and Spatial Awareness:**

Many kids with NLD have trouble understanding visual imagery. For example when they are asked to copy a shape like a cube they produce “profound distortions,” says Bezsylko. “These kids can’t accurately perceive the cube, the forms that make up the cube, and the relationships between them. Hence they can’t copy it.”

They also have difficulty evaluating visual-spatial information. This means they have trouble grasping the relationships between things they see and having a clear sense of where they are. This can make them physically awkward.

**2\. Higher-Order Comprehension:**

Higher-order comprehension is the ability to identify the main idea in something, the details that support the main idea, and the relationships among them. This affects kids’ ability to comprehend reading, and write or tell a story effectively.

It also affects taking notes. Bezsylko observed that some kids essentially take down everything the teacher says because they don’t know what’s important and what not to take down. Other kids don’t know what’s important so they take down nothing, and people think they aren’t paying attention. Or they take down all the wrong things.

**3\. Social Communication**

Most kids with non-verbal learning disorders have trouble reading emotion in facial cues and body language, so they often don’t know what’s going on in social interactions. They miss the social patterns that other kids pick up automatically, so they don’t know what’s appropriate behavior in a given situation.

Difficulties with social communication is one reason why kids with NLD often focus—sometimes obsessively—on technology. “In chat rooms or in a video game they don’t have to deal with all the nonverbal stuff,” Bezsylko notes.

**4\. Math Concepts**

Many kids with NLD are very good at rote learning, and they are able to do well in math just by memorizing data. But as they get older they struggle to solve more advanced mathematical problems that are based on recognizing concepts and patterns. Even with a problem they’ve seen before, if it’s approached differently or modified slightly, they have trouble recognizing it.

**5\. Executive Functions**

[Executive functions](https://childmind.org/article/helping-kids-who-struggle-with-executive-functions/) are a set of skills we use to organize our thinking, plan and carry out actions, and figure out how to solve problems. Most kids with NLD have weaknesses in these organizing and planning functions. For instance they struggle with breaking down a project into smaller pieces, or conceiving steps that need to be taken to get something done.

“These kids have trouble figuring things out—in fact they don’t really know what _figuring something out_ means,” Bezsylko says. “We have to help them learn to do that—the step-by-step process you go through.”

## How do these deficits manifest in kids with NLD?

In addition to the different combinations of symptoms, kids with NLD also vary along a spectrum of severity.

One the one hand there are kids who are extremely high-functioning but socially awkward, a little clumsy, disorganized—what Bezsylko calls “the absentminded professor type.” Other kids are more pervasively affected, and they function with more difficulty in many areas. “These kids often struggle to learn everything that isn’t rote or literal.”

At Winston Prep, a study of more than 100 students with NLD showed that there were 6 combinations of the 5 deficits. The largest group had all five of the deficits, but the second largest group had just two: social communication and executive functions.

## When do these deficits become noticeable?

Many kids with NLD symptoms can do well enough in elementary school because they are very good at memorization and rote learning. It’s common for them to run into trouble around middle school, when their difficulty with the higher order reasoning—figuring out the main idea, the details, and the relationships—causes them to fall behind. “There’s a saying that in fifth grade you stop learning to read, and now you read to learn,” notes Bezsylko, “and that’s when these kids fall apart.” Historically, Winston Prep took kids in sixth through tenth grade; they’ve started to take some kids as young as fourth grade.

“Almost all of these kids _look_ inattentive and disorganized,” Bezsylko adds, “especially as they get older. The more that schoolwork, math concepts, and socialization become complex rather than rote, the more those difficulties start to show up.”

## A more comprehensive diagnosis

NLD is not one of the official diagnoses mental health professionals and schools use to categorize kids with psychiatric or learning problems. Kids who have it usually have other diagnoses—often autism or [ADHD](https://childmind.org/topics/disorders/attention-deficit-hyperactivity-disorder/). But while those diagnoses list their symptoms or behaviors, they don’t fully explain them, argues Bezsylko.

For instance, if a child is disorganized and inattentive, he is likely to be diagnosed withADHD. But he may well be disorganized and inattentive _because_ he doesn’t understand what’s being discussed, what he reads, or the problem he’s been asked to solve. That’s where NLD comes in. “You can’t pay attention if you can’t understand,” notes Bezsylko.

Similarly, a child diagnosed withautism spectrum disorder will be described as having social and communication deficits. Those behaviors, too, can reflect NLD—not being able recognize patterns in facial expression, body language, and other forms of nonverbal communication can make kids unresponsive socially.

Take the kids in the Winston Prep study who had all five of the deficits. Most of them had a diagnosis of either ADHD or autism spectrum disorder. “But those diagnoses don’t identify three important areas where they are struggling,” notes Bezsylko: “higher-order comprehension, math concepts, and visual and spatial relations. Unless their NLD is recognized, they’re not likely to [get help](https://childmind.org/article/how-can-we-help-kids-with-non-verbal-learning-disorder/) that strengthens or compensates for weaknesses in those core areas.”

## Frequently Asked Questions

What is non-verbal learning disorder?

Is NLD on the autism spectrum?

This article was last reviewed or updated on October 30, 2023.

